# Numpy

## Creating Array

In [58]:
# thêm thư viện numpy
import numpy as np 
# tạo mảng 1 chiều từ 1 list
a = np.array([1,2,3,4,5])

print(a) #[1 2 3 4 5]
print(type(a)) #ndarray
print(a.shape) #5,

# index 
print(a[1]) #2
a[1] = 7 #thay đổi giá trị 
print(a[1]) #7

# tạo mảng 2 chiều 
b = np.array([[1,2,3], [4,5,6]])
print(b) #[[1,2,3]
         # [4,5,6]]
print(b.shape) #(2,4) 2 dòng 4 cột

# index 
print(b[0][0]) #1
print(b[1][2]) #6

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
2
7
[[1 2 3]
 [4 5 6]]
(2, 3)
1
6


In [69]:
# Một số hàm tạo mảng
a = np.arange(8) # tạo mảng 1 chiều từ 0->7
print(a)

newa = a.reshape(2,4) # newa thành mảng 2 chiều 2 dòng 4 cột, giữ nguyên a
print(newa)
print(a)

b = np.array([[1,2,3,4],[5,6,7,8]]) #reshape 2-D to 1-D
newb = b.reshape(-1)
print(newb) #[1 2 3 4 5 6 7 8]

#unknown dimesion 
b = np.array([1,2,3,4,5,6,7,8]) 
newb = b.reshape(2,2,-1) #thêm -1: chương trình tự tính toán chiều sao cho ma trận gồm các ma trận 2x2
print(newb) #1-D to 3-D
#[[[1 2]
#  [3 4]]

# [[5 6]
#  [7 8]]]


a = np.zeros((2,4)) # tạo mảng 2 chiều 2 dòng 4 cột các phần tử 0
print(a)

a = np.ones((2,4)) # tạo mảng 2 chiều 2 dòng 4 cột các phần tử 1
print(a)

a = np.random.random((2,2)) # tạo mảng 2 chiều 2 dòng 2 cột các phần tử bất kì 
print(a)

a = np.eye(2) # tạo ma trận đơn vị vuông cấp 2
print(a)

a = np.full((2,2), 5) # tạo mảng 2 chiều 2 dòng 2 cột các phần tử bằng 5
print(a)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.62749682 0.82579189]
 [0.85709415 0.92476526]]
[[1. 0.]
 [0. 1.]]
[[5 5]
 [5 5]]


## Array Indexing

In [43]:
# truy cập bằng slicing array
c = [1,2,3,4,5,6,7,8,9,10] # mảng 1 chiều 
print(c[1:7:2]) #start = 1, end = 7, step = 2
print(c[-3:-1])

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a[0][2]) #3
b = a[:2, :2]
print(b) # [[1 2]
         #  [5 6]]

# khi sử dụng slicing array b là 1 chế độ xem của a nên chỉnh sửa b cũng làm thay đổi a
print(a[0][1]) #2
b[0][1] = 3 # => a[0][1] = 3
print(a[0][1]) #3
print(a[:2, :2]) #[[1 3]
                 # [5 6]]

[2, 4, 6]
[8, 9]
3
[[1 2]
 [5 6]]
2
3
[[1 3]
 [5 6]]


In [36]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 2 cách truy cập dữ liệu mảng 
row_r1 = a[:1,1:4] 
print(row_r1) # [[2 3 4]]
print(row_r1.shape) # (1,3) => giữ nguyên chiều của mảng ban đầu

row_r2 = a[0,1:4]
print(row_r2) #[2 3 4]
print(row_r2.shape) #(3,) => chiều giảm 1 so với mảng ban đầu 

# ==>> nếu ở cả hai đều sử dụng slicing thì chiều giữ nguyên, kiểu số với slicing sẽ giảm chiều đi 1  

[[2 3 4]]
(1, 3)
[2 3 4]
(3,)


In [46]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [55]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])
            
b = np.array([1,2,3,4])
print(b[[0, 1]]) #[1 2]
b[[0,1]] += 5
print(b[[0 ,1]]) #[6 7]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
[1 2]
[6 7]


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

## Data Types

In [59]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


## Copy and View

In [67]:
a = np.array([1,2,3,4,5])

#copy() tạo ra mảng mới với các giá trị được sao chép từ mảng ban đầu
x = a.copy()
a[0] = 42 #thay đổi trong a không làm ảnh hưởng tới x và ngược lại
print(x) #[1 2 3 4 5]
print(a) #[42  2  3  4  5]
x[0] = 2
print(a) #[42  2  3  4  5]
print(x) #[2 2 3 4 5]

#view() chỉ là chế độ xem, thay đổi giá trị a làm thay đổi y và ngược lại thay đổi y làm thay đổi a
y = a.view()
a[0] = 43
print(a) #[43  2  3  4  5]
print(y) #[43  2  3  4  5]
y[0] = 1
print(a) #[1 2 3 4 5]
print(y) #[1 2 3 4 5]

#kiểm tra xem mảng chứa dữ liệu của nó (được copy sang) hay không (view). Nếu chứa dữ liệu của nó return None, không thì trả về mảng gốc
print(x.base) #None vì chứa dữ liệu của nó 
print(y.base) #[1 2 3 4 5]

[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[2 2 3 4 5]
[43  2  3  4  5]
[43  2  3  4  5]
[1 2 3 4 5]
[1 2 3 4 5]
None
[1 2 3 4 5]


## Array Math

In [70]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [71]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [72]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [73]:
# ma trận chuyển vị
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting

Broadcasting là một cơ chế mạnh mẽ cho phép numpy hoạt động với các mảng có hình dạng khác nhau khi thực hiện các phép toán số học. Chúng ta thường có một mảng nhỏ hơn và một mảng lớn hơn và chúng ta muốn sử dụng mảng nhỏ hơn nhiều lần để thực hiện một số thao tác trên mảng lớn hơn.

Ví dụ: giả sử rằng chúng ta muốn cộng một vectơ không đổi vào mỗi hàng của ma trận. Chúng ta có thể làm như thế này:

In [74]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Khi ma trận x rất lớn, việc tính toán một vòng lặp rõ ràng trong Python có thể bị chậm. Lưu ý rằng cộng thêm vectơ v vào mỗi hàng của ma trận x tương đương với việc hình thành ma trận vv bằng cách xếp chồng nhiều bản sao của v theo chiều dọc, sau đó thực hiện phép tính tổng của x và vv. Chúng ta có thể thực hiện phương pháp này như thế này:

In [77]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [78]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]



Numpy broadcasting cho phép chúng tôi thực hiện tính toán này mà không thực sự tạo ra nhiều bản sao của v. Hãy xem xét cách làm này, sử dụng broadcasting:

Dòng y = x + v hoạt động ngay cả khi x có shape (4, 3) và v có shape (3,), do broadcasting dòng này hoạt động như thể v thực sự có hình dạng (4, 3), trong đó mỗi hàng là một bản sao của v và tổng được thực hiện theo từng phần tử.

Broadcasting hai mảng với nhau theo các quy tắc sau (Mình xin phép không dịch):

If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible in all dimensions.
After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

In [79]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
